service: btar
image: eidj/btar

servers:
  web:
    - 37.59.100.208

accessories:
  db:
    image: postgres:16
    host: 37.59.100.208
    port: 5432
    env:
      clear:
        POSTGRES_USER: btar
        POSTGRES_DB: btar_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

ssh:
  user: deploy

proxy:
  ssl: false
  host: 37.59.100.208
  app_port: 80

registry:
  username: eidj
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    DB_HOST: 37.59.100.208   # Postgres sur l'hôte (bridge docker)
  secret:
    - RAILS_MASTER_KEY
    - BTAR_DATABASE_PASSWORD

volumes:
  - "storage:/rails/storage"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
  migrate: app exec --reuse "bin/rails db:migrate"

builder:
  arch: amd64